### ISSUE TITLE
[Bug] 'REST' object has no attribute 'get_last_trade'

### ISSUE THREAD

**Issue by sshcli** [tejaslinge/Alpaca-Trading-Bot#11]
'REST' object has no attribute 'get_last_trade'

Python 3.10
alpaca_trade_api==2.0.0
pandas==1.4.1
numpy==1.22.3

**Comment by sshcli** [comment]
Official response from alpaca-trade-api-python repo:

> Hey @sshcli the get_last_trade and get_last_quote functions were deprecated a while back with the other market-data v1 functionality and were replaced with get_latest_trade and get_latest_quote.

**Comment by tejaslinge** [comment]
Hey @sshcli, thanks a lot for bringing this to my attention. I've updated it in the code.

**Comment by sshcli** [comment]
Thanks to you @tejaslinge for your kind support.

For documentation purpose, I'm leaving here the referencie of the commit:
https://github.com/tejaslinge/Alpaca-Trading-Bot/commit/a0e1582309b19ff58651deefc23895c7ea426917
 
I didn't make a PR right away for this change because I was waiting until tomorrow Monday to test it when the market is open.

I have created another PR as a second part.  
https://github.com/tejaslinge/Alpaca-Trading-Bot/pull/12
